spring:
  shardingsphere:
    datasource:
      names: m0
      m0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=true
        username: root
        password: root
    sharding:
      tables:
        user:
          actual-data-nodes: m0.user_$->{0..1}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 2}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    lazyLoadingEnabled: false
  global-config:
    banner: false
    sql-parser-cache: true
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true